extends:
  - "airbnb"
  - "airbnb-typescript"
parserOptions:
  project: "./tsconfig.json"
env:
  browser: true
rules:
  "react/jsx-filename-extension": [ 2, { 'extensions': [ '.js', '.jsx', '.ts', '.tsx' ] } ]
  "react/button-has-type": "off"
  "react/jsx-props-no-spreading": "off"
  "import/prefer-default-export": "off"
  "react/require-default-props": "off"
  "no-param-reassign": "off"
  "react/function-component-definition": "off"
